import type { AddressFields } from './address-fields'

export type RateSeedListing = {
  id: string
  /** Short label for buttons */
  label: string
  /** One-line description of the corridor */
  description: string
  shipFrom: AddressFields
  shipTo: AddressFields
}

const baseResidential = 'no' as const

/**
 * Preset ship-from / ship-to pairs for the admin rate calculator (demo and QA).
 */
export const RATE_SEED_LISTINGS: RateSeedListing[] = [
  {
    id: 'socal-east',
    label: 'SoCal → East Coast',
    description: 'Oceanside, CA → Boston, MA',
    shipFrom: {
      name: 'SoCal warehouse',
      phone: '555-0101',
      company_name: '',
      address_line1: '300 N Coast Hwy',
      address_line2: '',
      city_locality: 'Oceanside',
      state_province: 'CA',
      postal_code: '92054',
      country_code: 'US',
      residential: baseResidential,
    },
    shipTo: {
      name: 'East Coast recipient',
      phone: '555-0201',
      company_name: '',
      address_line1: '100 Federal St',
      address_line2: 'Suite 400',
      city_locality: 'Boston',
      state_province: 'MA',
      postal_code: '02110',
      country_code: 'US',
      residential: baseResidential,
    },
  },
  {
    id: 'norcal-texas',
    label: 'NorCal → Texas',
    description: 'San Francisco, CA → Houston, TX',
    shipFrom: {
      name: 'Bay Area shipper',
      phone: '555-0102',
      company_name: '',
      address_line1: '1 Ferry Building',
      address_line2: '',
      city_locality: 'San Francisco',
      state_province: 'CA',
      postal_code: '94111',
      country_code: 'US',
      residential: baseResidential,
    },
    shipTo: {
      name: 'Texas recipient',
      phone: '555-0202',
      company_name: '',
      address_line1: '1600 Smith St',
      address_line2: '',
      city_locality: 'Houston',
      state_province: 'TX',
      postal_code: '77002',
      country_code: 'US',
      residential: baseResidential,
    },
  },
  {
    id: 'ny-sb',
    label: 'New York → Santa Barbara',
    description: 'New York, NY → Santa Barbara, CA',
    shipFrom: {
      name: 'New York shipper',
      phone: '555-0108',
      company_name: '',
      address_line1: '450 W 33rd St',
      address_line2: '',
      city_locality: 'New York',
      state_province: 'NY',
      postal_code: '10001',
      country_code: 'US',
      residential: baseResidential,
    },
    shipTo: {
      name: 'Santa Barbara recipient',
      phone: '555-0208',
      company_name: '',
      address_line1: '701 State St',
      address_line2: '',
      city_locality: 'Santa Barbara',
      state_province: 'CA',
      postal_code: '93101',
      country_code: 'US',
      residential: baseResidential,
    },
  },
  {
    id: 'socal-oahu',
    label: 'SoCal → Oʻahu',
    description: 'Los Angeles, CA → Honolulu, HI',
    shipFrom: {
      name: 'LA fulfillment',
      phone: '555-0103',
      company_name: '',
      address_line1: '1200 Getty Center Dr',
      address_line2: '',
      city_locality: 'Los Angeles',
      state_province: 'CA',
      postal_code: '90049',
      country_code: 'US',
      residential: baseResidential,
    },
    shipTo: {
      name: 'Honolulu recipient',
      phone: '555-0203',
      company_name: '',
      address_line1: '2335 Kalakaua Ave',
      address_line2: '',
      city_locality: 'Honolulu',
      state_province: 'HI',
      postal_code: '96815',
      country_code: 'US',
      residential: baseResidential,
    },
  },
  {
    id: 'sf-sd',
    label: 'San Francisco → San Diego',
    description: 'San Francisco, CA → San Diego, CA',
    shipFrom: {
      name: 'SF shipper',
      phone: '555-0104',
      company_name: '',
      address_line1: '1 Market St',
      address_line2: '',
      city_locality: 'San Francisco',
      state_province: 'CA',
      postal_code: '94105',
      country_code: 'US',
      residential: baseResidential,
    },
    shipTo: {
      name: 'San Diego recipient',
      phone: '555-0204',
      company_name: '',
      address_line1: '750 A St',
      address_line2: '',
      city_locality: 'San Diego',
      state_province: 'CA',
      postal_code: '92101',
      country_code: 'US',
      residential: baseResidential,
    },
  },
  {
    id: 'sd-newport',
    label: 'San Diego → Newport',
    description: 'San Diego, CA → Newport Beach, CA',
    shipFrom: {
      name: 'San Diego shipper',
      phone: '555-0105',
      company_name: '',
      address_line1: '750 A St',
      address_line2: '',
      city_locality: 'San Diego',
      state_province: 'CA',
      postal_code: '92101',
      country_code: 'US',
      residential: baseResidential,
    },
    shipTo: {
      name: 'Newport recipient',
      phone: '555-0205',
      company_name: '',
      address_line1: '2100 Newport Blvd',
      address_line2: '',
      city_locality: 'Newport Beach',
      state_province: 'CA',
      postal_code: '92663',
      country_code: 'US',
      residential: baseResidential,
    },
  },
  {
    id: 'sb-sc',
    label: 'Santa Barbara → Santa Cruz',
    description: 'Santa Barbara, CA → Santa Cruz, CA',
    shipFrom: {
      name: 'Santa Barbara shipper',
      phone: '555-0106',
      company_name: '',
      address_line1: '500 State St',
      address_line2: '',
      city_locality: 'Santa Barbara',
      state_province: 'CA',
      postal_code: '93101',
      country_code: 'US',
      residential: baseResidential,
    },
    shipTo: {
      name: 'Santa Cruz recipient',
      phone: '555-0206',
      company_name: '',
      address_line1: '1200 Pacific Ave',
      address_line2: '',
      city_locality: 'Santa Cruz',
      state_province: 'CA',
      postal_code: '95060',
      country_code: 'US',
      residential: baseResidential,
    },
  },
  {
    id: 'sc-sd',
    label: 'Santa Cruz → San Diego',
    description: 'Santa Cruz, CA → San Diego, CA',
    shipFrom: {
      name: 'Santa Cruz shipper',
      phone: '555-0107',
      company_name: '',
      address_line1: '1200 Pacific Ave',
      address_line2: '',
      city_locality: 'Santa Cruz',
      state_province: 'CA',
      postal_code: '95060',
      country_code: 'US',
      residential: baseResidential,
    },
    shipTo: {
      name: 'San Diego recipient',
      phone: '555-0207',
      company_name: '',
      address_line1: '750 A St',
      address_line2: '',
      city_locality: 'San Diego',
      state_province: 'CA',
      postal_code: '92101',
      country_code: 'US',
      residential: baseResidential,
    },
  },
  {
    id: 'socal-florida',
    label: 'SoCal → Florida',
    description: 'San Clemente, CA → Miami, FL',
    shipFrom: {
      name: 'San Clemente shipper',
      phone: '555-0109',
      company_name: '',
      address_line1: '101 N El Camino Real',
      address_line2: '',
      city_locality: 'San Clemente',
      state_province: 'CA',
      postal_code: '92672',
      country_code: 'US',
      residential: baseResidential,
    },
    shipTo: {
      name: 'Miami recipient',
      phone: '555-0209',
      company_name: '',
      address_line1: '100 S Biscayne Blvd',
      address_line2: '',
      city_locality: 'Miami',
      state_province: 'FL',
      postal_code: '33131',
      country_code: 'US',
      residential: baseResidential,
    },
  },
  {
    id: 'pnw-socal',
    label: 'PNW → SoCal',
    description: 'Seattle, WA → Huntington Beach, CA',
    shipFrom: {
      name: 'Seattle shipper',
      phone: '555-0110',
      company_name: '',
      address_line1: '400 Broad St',
      address_line2: '',
      city_locality: 'Seattle',
      state_province: 'WA',
      postal_code: '98109',
      country_code: 'US',
      residential: baseResidential,
    },
    shipTo: {
      name: 'Huntington Beach recipient',
      phone: '555-0210',
      company_name: '',
      address_line1: '200 Main St',
      address_line2: '',
      city_locality: 'Huntington Beach',
      state_province: 'CA',
      postal_code: '92648',
      country_code: 'US',
      residential: baseResidential,
    },
  },
  {
    id: 'socal-midwest',
    label: 'SoCal → Midwest',
    description: 'Ventura, CA → Chicago, IL',
    shipFrom: {
      name: 'Ventura shipper',
      phone: '555-0111',
      company_name: '',
      address_line1: '255 S Seaward Ave',
      address_line2: '',
      city_locality: 'Ventura',
      state_province: 'CA',
      postal_code: '93001',
      country_code: 'US',
      residential: baseResidential,
    },
    shipTo: {
      name: 'Chicago recipient',
      phone: '555-0211',
      company_name: '',
      address_line1: '233 S Wacker Dr',
      address_line2: '',
      city_locality: 'Chicago',
      state_province: 'IL',
      postal_code: '60606',
      country_code: 'US',
      residential: baseResidential,
    },
  },
  {
    id: 'east-socal-res',
    label: 'East → SoCal (residential)',
    description: 'Brooklyn, NY → Encinitas, CA — residential delivery',
    shipFrom: {
      name: 'Brooklyn shipper',
      phone: '555-0112',
      company_name: '',
      address_line1: '1 Pierrepont St',
      address_line2: '',
      city_locality: 'Brooklyn',
      state_province: 'NY',
      postal_code: '11201',
      country_code: 'US',
      residential: 'yes',
    },
    shipTo: {
      name: 'Encinitas recipient',
      phone: '555-0212',
      company_name: '',
      address_line1: '450 S Coast Hwy 101',
      address_line2: '',
      city_locality: 'Encinitas',
      state_province: 'CA',
      postal_code: '92024',
      country_code: 'US',
      residential: 'yes',
    },
  },
]
