-- Public feature-request and bug board (/feature-requests) plus changelog.
-- Members post, vote, and comment. Staff set status, estimates, and changelog entries.
-- Vote and comment totals are maintained by triggers so clients cannot write them.

CREATE TABLE IF NOT EXISTS public.feature_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  number integer GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1) NOT NULL,
  kind text NOT NULL CHECK (kind IN ('feature', 'bug')),
  title text NOT NULL,
  body text NOT NULL,
  status text NOT NULL DEFAULT 'idea' CHECK (
    status IN ('idea', 'under_review', 'planned', 'in_progress', 'shipped', 'closed')
  ),
  author_id uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  tags text[] NOT NULL DEFAULT '{}',
  estimated_label text,
  vote_count integer NOT NULL DEFAULT 0 CHECK (vote_count >= 0),
  comment_count integer NOT NULL DEFAULT 0 CHECK (comment_count >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT feature_requests_number_key UNIQUE (number)
);

CREATE TABLE IF NOT EXISTS public.feature_request_votes (
  request_id uuid NOT NULL REFERENCES public.feature_requests (id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (request_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.feature_request_comments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  request_id uuid NOT NULL REFERENCES public.feature_requests (id) ON DELETE CASCADE,
  author_id uuid NOT NULL REFERENCES public.profiles (id) ON DELETE CASCADE,
  body text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.feature_request_changelog (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  request_id uuid REFERENCES public.feature_requests (id) ON DELETE SET NULL,
  title text NOT NULL,
  body text NOT NULL,
  published_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid REFERENCES public.profiles (id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS feature_request_changelog_request_uidx
  ON public.feature_request_changelog (request_id)
  WHERE request_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS feature_requests_open_votes_idx
  ON public.feature_requests (vote_count DESC, created_at DESC)
  WHERE status IN ('idea', 'under_review', 'planned', 'in_progress');

CREATE INDEX IF NOT EXISTS feature_requests_status_votes_idx
  ON public.feature_requests (status, vote_count DESC, created_at DESC);

CREATE INDEX IF NOT EXISTS feature_requests_created_idx
  ON public.feature_requests (created_at DESC);

CREATE INDEX IF NOT EXISTS feature_requests_comment_count_idx
  ON public.feature_requests (comment_count DESC, created_at DESC);

CREATE INDEX IF NOT EXISTS feature_requests_author_created_idx
  ON public.feature_requests (author_id, created_at DESC);

CREATE INDEX IF NOT EXISTS feature_request_comments_request_idx
  ON public.feature_request_comments (request_id, created_at);

CREATE INDEX IF NOT EXISTS feature_request_comments_author_created_idx
  ON public.feature_request_comments (author_id, created_at DESC);

CREATE INDEX IF NOT EXISTS feature_request_changelog_published_idx
  ON public.feature_request_changelog (published_at DESC);

CREATE OR REPLACE FUNCTION public.feature_requests_normalize()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  allowed text[] := ARRAY['buying', 'selling', 'app', 'web', 'offers', 'shipping', 'search'];
  cleaned text[] := '{}';
  tag text;
  staff boolean;
BEGIN
  staff := public.is_admin_or_employee();

  NEW.title := trim(NEW.title);
  NEW.body := trim(NEW.body);

  IF char_length(NEW.title) < 4 OR char_length(NEW.title) > 140 THEN
    RAISE EXCEPTION 'invalid feature request title';
  END IF;
  IF char_length(NEW.body) < 10 OR char_length(NEW.body) > 5000 THEN
    RAISE EXCEPTION 'invalid feature request body';
  END IF;

  IF NEW.estimated_label IS NOT NULL THEN
    NEW.estimated_label := nullif(trim(NEW.estimated_label), '');
    IF NEW.estimated_label IS NOT NULL AND char_length(NEW.estimated_label) > 40 THEN
      RAISE EXCEPTION 'invalid feature request estimate';
    END IF;
  END IF;

  IF NEW.tags IS NULL THEN
    NEW.tags := '{}';
  END IF;
  FOREACH tag IN ARRAY NEW.tags LOOP
    tag := lower(trim(tag));
    IF tag = ANY (allowed) AND NOT tag = ANY (cleaned) THEN
      cleaned := array_append(cleaned, tag);
    END IF;
  END LOOP;
  IF cardinality(cleaned) > 4 THEN
    cleaned := cleaned[1:4];
  END IF;
  NEW.tags := cleaned;

  IF TG_OP = 'INSERT' THEN
    NEW.status := 'idea';
    NEW.estimated_label := NULL;
    NEW.vote_count := 0;
    NEW.comment_count := 0;
    IF NOT staff THEN
      NEW.author_id := auth.uid();
    END IF;
    NEW.updated_at := now();
    RETURN NEW;
  END IF;

  IF current_setting('feature_requests.internal', true) = '1' THEN
    RETURN NEW;
  END IF;

  NEW.author_id := OLD.author_id;
  NEW.number := OLD.number;
  NEW.created_at := OLD.created_at;
  NEW.vote_count := OLD.vote_count;
  NEW.comment_count := OLD.comment_count;
  NEW.updated_at := now();

  IF NOT staff THEN
    NEW.status := OLD.status;
    NEW.kind := OLD.kind;
    NEW.tags := OLD.tags;
    NEW.estimated_label := OLD.estimated_label;
    IF OLD.status IN ('shipped', 'closed') THEN
      NEW.title := OLD.title;
      NEW.body := OLD.body;
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS feature_requests_normalize ON public.feature_requests;
CREATE TRIGGER feature_requests_normalize
  BEFORE INSERT OR UPDATE ON public.feature_requests
  FOR EACH ROW
  EXECUTE FUNCTION public.feature_requests_normalize();

CREATE OR REPLACE FUNCTION public.feature_requests_set_vote_count()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  target uuid := COALESCE(NEW.request_id, OLD.request_id);
BEGIN
  PERFORM set_config('feature_requests.internal', '1', true);
  UPDATE public.feature_requests
  SET vote_count = (
    SELECT count(*)::integer
    FROM public.feature_request_votes v
    WHERE v.request_id = target
  )
  WHERE id = target;
  PERFORM set_config('feature_requests.internal', '', true);
  RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS feature_request_votes_sync_count ON public.feature_request_votes;
CREATE TRIGGER feature_request_votes_sync_count
  AFTER INSERT OR DELETE ON public.feature_request_votes
  FOR EACH ROW
  EXECUTE FUNCTION public.feature_requests_set_vote_count();

CREATE OR REPLACE FUNCTION public.feature_request_comments_normalize()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.body := trim(NEW.body);
  IF char_length(NEW.body) < 1 OR char_length(NEW.body) > 2000 THEN
    RAISE EXCEPTION 'invalid feature request comment';
  END IF;
  IF TG_OP = 'INSERT' AND NOT public.is_admin_or_employee() THEN
    NEW.author_id := auth.uid();
  END IF;
  IF TG_OP = 'UPDATE' THEN
    NEW.request_id := OLD.request_id;
    NEW.created_at := OLD.created_at;
    IF NOT public.is_admin_or_employee() THEN
      NEW.author_id := OLD.author_id;
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS feature_request_comments_normalize ON public.feature_request_comments;
CREATE TRIGGER feature_request_comments_normalize
  BEFORE INSERT OR UPDATE ON public.feature_request_comments
  FOR EACH ROW
  EXECUTE FUNCTION public.feature_request_comments_normalize();

CREATE OR REPLACE FUNCTION public.feature_request_comments_set_count()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  target uuid := COALESCE(NEW.request_id, OLD.request_id);
BEGIN
  PERFORM set_config('feature_requests.internal', '1', true);
  UPDATE public.feature_requests
  SET comment_count = (
    SELECT count(*)::integer
    FROM public.feature_request_comments c
    WHERE c.request_id = target
  )
  WHERE id = target;
  PERFORM set_config('feature_requests.internal', '', true);
  RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS feature_request_comments_sync_count ON public.feature_request_comments;
CREATE TRIGGER feature_request_comments_sync_count
  AFTER INSERT OR DELETE ON public.feature_request_comments
  FOR EACH ROW
  EXECUTE FUNCTION public.feature_request_comments_set_count();

CREATE OR REPLACE FUNCTION public.feature_request_changelog_touch()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.title := trim(NEW.title);
  NEW.body := trim(NEW.body);
  IF char_length(NEW.title) < 4 OR char_length(NEW.title) > 140 THEN
    RAISE EXCEPTION 'invalid changelog title';
  END IF;
  IF char_length(NEW.body) < 10 OR char_length(NEW.body) > 5000 THEN
    RAISE EXCEPTION 'invalid changelog body';
  END IF;
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS feature_request_changelog_touch ON public.feature_request_changelog;
CREATE TRIGGER feature_request_changelog_touch
  BEFORE INSERT OR UPDATE ON public.feature_request_changelog
  FOR EACH ROW
  EXECUTE FUNCTION public.feature_request_changelog_touch();

ALTER TABLE public.feature_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feature_request_votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feature_request_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feature_request_changelog ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "feature_requests_select_public" ON public.feature_requests;
CREATE POLICY "feature_requests_select_public" ON public.feature_requests
  FOR SELECT TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS "feature_requests_insert_own" ON public.feature_requests;
CREATE POLICY "feature_requests_insert_own" ON public.feature_requests
  FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = author_id AND status = 'idea');

DROP POLICY IF EXISTS "feature_requests_update_author_or_staff" ON public.feature_requests;
CREATE POLICY "feature_requests_update_author_or_staff" ON public.feature_requests
  FOR UPDATE TO authenticated
  USING (author_id = auth.uid() OR public.is_admin_or_employee())
  WITH CHECK (author_id = auth.uid() OR public.is_admin_or_employee());

DROP POLICY IF EXISTS "feature_requests_delete_staff" ON public.feature_requests;
CREATE POLICY "feature_requests_delete_staff" ON public.feature_requests
  FOR DELETE TO authenticated
  USING (public.is_admin_or_employee());

DROP POLICY IF EXISTS "feature_request_votes_select_own" ON public.feature_request_votes;
CREATE POLICY "feature_request_votes_select_own" ON public.feature_request_votes
  FOR SELECT TO authenticated
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "feature_request_votes_insert_own" ON public.feature_request_votes;
CREATE POLICY "feature_request_votes_insert_own" ON public.feature_request_votes
  FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "feature_request_votes_delete_own" ON public.feature_request_votes;
CREATE POLICY "feature_request_votes_delete_own" ON public.feature_request_votes
  FOR DELETE TO authenticated
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "feature_request_comments_select_public" ON public.feature_request_comments;
CREATE POLICY "feature_request_comments_select_public" ON public.feature_request_comments
  FOR SELECT TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS "feature_request_comments_insert_own" ON public.feature_request_comments;
CREATE POLICY "feature_request_comments_insert_own" ON public.feature_request_comments
  FOR INSERT TO authenticated
  WITH CHECK (author_id = auth.uid());

DROP POLICY IF EXISTS "feature_request_comments_delete_own_or_staff" ON public.feature_request_comments;
CREATE POLICY "feature_request_comments_delete_own_or_staff" ON public.feature_request_comments
  FOR DELETE TO authenticated
  USING (author_id = auth.uid() OR public.is_admin_or_employee());

DROP POLICY IF EXISTS "feature_request_changelog_select_public" ON public.feature_request_changelog;
CREATE POLICY "feature_request_changelog_select_public" ON public.feature_request_changelog
  FOR SELECT TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS "feature_request_changelog_insert_staff" ON public.feature_request_changelog;
CREATE POLICY "feature_request_changelog_insert_staff" ON public.feature_request_changelog
  FOR INSERT TO authenticated
  WITH CHECK (public.is_admin_or_employee() AND created_by = auth.uid());

DROP POLICY IF EXISTS "feature_request_changelog_update_staff" ON public.feature_request_changelog;
CREATE POLICY "feature_request_changelog_update_staff" ON public.feature_request_changelog
  FOR UPDATE TO authenticated
  USING (public.is_admin_or_employee())
  WITH CHECK (public.is_admin_or_employee());

DROP POLICY IF EXISTS "feature_request_changelog_delete_staff" ON public.feature_request_changelog;
CREATE POLICY "feature_request_changelog_delete_staff" ON public.feature_request_changelog
  FOR DELETE TO authenticated
  USING (public.is_admin_or_employee());

REVOKE ALL ON FUNCTION public.feature_requests_normalize() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.feature_requests_set_vote_count() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.feature_request_comments_normalize() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.feature_request_comments_set_count() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.feature_request_changelog_touch() FROM PUBLIC;

COMMENT ON TABLE public.feature_requests IS
  'Member feature ideas and bug reports for the public /feature-requests board.';
COMMENT ON TABLE public.feature_request_changelog IS
  'Shipped notes published from the feature request board.';

NOTIFY pgrst, 'reload schema';
