import type { User } from "@supabase/supabase-js"

import { validateDisplayName } from "@/lib/display-name-validation"

/** Matches the DB trigger fallback: `User` + first 8 hex chars of UUID (no dashes). */
const AUTO_DISPLAY_NAME_RE = /^User[a-f0-9]{8}$/i

export type ProfileCompletionRow = {
  display_name: string | null
  avatar_url: string | null
  profile_completed_at: string | null
  email: string | null
}

export function isAutoGeneratedDisplayName(name: string | null | undefined): boolean {
  const trimmed = name?.trim()
  if (!trimmed) return false
  return AUTO_DISPLAY_NAME_RE.test(trimmed)
}

export function getOAuthAvatarUrl(user: User): string | null {
  const meta = user.user_metadata as Record<string, unknown> | undefined
  const fromMeta =
    (typeof meta?.avatar_url === "string" && meta.avatar_url.trim()) ||
    (typeof meta?.picture === "string" && meta.picture.trim()) ||
    ""
  return fromMeta || null
}

function pickValidDisplayName(
  candidate: string | null | undefined,
  userEmail: string | null | undefined,
): string | null {
  const trimmed = candidate?.trim()
  if (!trimmed || isAutoGeneratedDisplayName(trimmed)) return null
  const check = validateDisplayName(trimmed, userEmail)
  return check.valid ? trimmed : null
}

/**
 * Prefill for the post-signup modal: prefer user-chosen metadata, then profile, then OAuth name.
 */
export function suggestProfileCompletionDisplayName(
  profile: ProfileCompletionRow | null | undefined,
  user: User,
): string {
  const email = profile?.email?.trim() || user.email?.trim() || null
  const meta = user.user_metadata as Record<string, unknown> | undefined

  const fromMetaDisplay =
    typeof meta?.display_name === "string" ? meta.display_name : null
  const fromProfile = profile?.display_name ?? null
  const fromOAuthName =
    (typeof meta?.full_name === "string" && meta.full_name) ||
    (typeof meta?.name === "string" && meta.name) ||
    null

  return (
    pickValidDisplayName(fromMetaDisplay, email) ??
    pickValidDisplayName(fromProfile, email) ??
    pickValidDisplayName(fromOAuthName, email) ??
    ""
  )
}

export function profileNeedsCompletion(
  profile: ProfileCompletionRow | null | undefined,
): boolean {
  return !profile?.profile_completed_at
}

export function isGoogleAuthUser(user: User): boolean {
  const am = user.app_metadata ?? {}
  const providers = am.providers
  if (Array.isArray(providers) && providers.some((p) => String(p).toLowerCase() === "google")) {
    return true
  }
  if (typeof am.provider === "string" && am.provider.toLowerCase() === "google") {
    return true
  }
  return user.identities?.some((identity) => identity.provider === "google") ?? false
}

/** Google sign-in users who still need to choose a username after account creation. */
export function userNeedsGoogleProfileCompletion(
  user: User,
  profile: ProfileCompletionRow | null | undefined,
): boolean {
  return isGoogleAuthUser(user) && profileNeedsCompletion(profile)
}

/**
 * Email/password sign-ups collect a display name in the form; Google users must pick a username here.
 */
export function suggestProfileCompletionUsername(
  profile: ProfileCompletionRow | null | undefined,
  user: User,
): string {
  if (isGoogleAuthUser(user)) return ""
  return suggestProfileCompletionDisplayName(profile, user)
}
