import type { SupabaseClient, User } from "@supabase/supabase-js"

import { validateDisplayName } from "@/lib/display-name-validation"

/** Matches the DB trigger fallback: `User` + first 8 hex chars of UUID (no dashes). */
const AUTO_DISPLAY_NAME_RE = /^User[a-f0-9]{8}$/i

/** Generous window for OAuth redirects / slow first paint when DB column is missing. */
export const GOOGLE_PROFILE_SETUP_WINDOW_MS = 30 * 60 * 1000

export const PROFILE_USERNAME_COMPLETED_METADATA_KEY = "profile_username_completed"

export type ProfileCompletionRow = {
  display_name: string | null
  avatar_url: string | null
  profile_completed_at: string | null
  email: string | null
}

export type ProfileCompletionFetchResult = {
  profile: ProfileCompletionRow | null
  hasCompletionColumn: boolean
  error: string | null
}

export function isAutoGeneratedDisplayName(name: string | null | undefined): boolean {
  const trimmed = name?.trim()
  if (!trimmed) return false
  return AUTO_DISPLAY_NAME_RE.test(trimmed)
}

export function getOAuthAvatarUrl(user: User): string | null {
  const meta = user.user_metadata as Record<string, unknown> | undefined
  const fromMeta =
    (typeof meta?.avatar_url === "string" && meta.avatar_url.trim()) ||
    (typeof meta?.picture === "string" && meta.picture.trim()) ||
    ""
  return fromMeta || null
}

export function hasCompletedProfileUsername(user: User): boolean {
  const meta = user.user_metadata as Record<string, unknown> | undefined
  return meta?.[PROFILE_USERNAME_COMPLETED_METADATA_KEY] === true
}

export function isRecentOAuthSignup(user: User): boolean {
  const created = new Date(user.created_at).getTime()
  return Number.isFinite(created) && Date.now() - created < GOOGLE_PROFILE_SETUP_WINDOW_MS
}

function pickValidDisplayName(
  candidate: string | null | undefined,
  userEmail: string | null | undefined,
): string | null {
  const trimmed = candidate?.trim()
  if (!trimmed || isAutoGeneratedDisplayName(trimmed)) return null
  const check = validateDisplayName(trimmed, userEmail)
  return check.valid ? trimmed : null
}

/**
 * Prefill for the post-signup modal: prefer user-chosen metadata, then profile, then OAuth name.
 */
export function suggestProfileCompletionDisplayName(
  profile: ProfileCompletionRow | null | undefined,
  user: User,
): string {
  const email = profile?.email?.trim() || user.email?.trim() || null
  const meta = user.user_metadata as Record<string, unknown> | undefined

  const fromMetaDisplay =
    typeof meta?.display_name === "string" ? meta.display_name : null
  const fromProfile = profile?.display_name ?? null
  const fromOAuthName =
    (typeof meta?.full_name === "string" && meta.full_name) ||
    (typeof meta?.name === "string" && meta.name) ||
    null

  return (
    pickValidDisplayName(fromMetaDisplay, email) ??
    pickValidDisplayName(fromProfile, email) ??
    pickValidDisplayName(fromOAuthName, email) ??
    ""
  )
}

export function profileNeedsCompletion(
  profile: ProfileCompletionRow | null | undefined,
  hasCompletionColumn = true,
): boolean {
  if (!hasCompletionColumn) return false
  return !profile?.profile_completed_at
}

export function isGoogleAuthUser(user: User): boolean {
  const am = user.app_metadata ?? {}
  const providers = am.providers
  if (Array.isArray(providers) && providers.some((p) => String(p).toLowerCase() === "google")) {
    return true
  }
  if (typeof am.provider === "string" && am.provider.toLowerCase() === "google") {
    return true
  }
  if (user.identities?.some((identity) => identity.provider === "google")) {
    return true
  }

  const meta = user.user_metadata as Record<string, unknown> | undefined
  const iss = typeof meta?.iss === "string" ? meta.iss : ""
  if (iss.includes("accounts.google.com")) return true

  return false
}

/** Google sign-in users who still need to choose a username after account creation. */
export function userNeedsGoogleProfileCompletion(
  user: User,
  profile: ProfileCompletionRow | null | undefined,
  options?: { hasCompletionColumn?: boolean },
): boolean {
  if (!isGoogleAuthUser(user)) return false
  if (hasCompletedProfileUsername(user)) return false

  const hasCompletionColumn = options?.hasCompletionColumn !== false

  if (hasCompletionColumn) {
    return profileNeedsCompletion(profile, true)
  }

  return isRecentOAuthSignup(user)
}

/**
 * Email/password sign-ups collect a display name in the form; Google users must pick a username here.
 */
export function suggestProfileCompletionUsername(
  profile: ProfileCompletionRow | null | undefined,
  user: User,
): string {
  if (isGoogleAuthUser(user)) return ""
  return suggestProfileCompletionDisplayName(profile, user)
}

function isMissingProfileCompletedColumnError(error: {
  message?: string
  code?: string
}): boolean {
  const msg = error.message?.toLowerCase() ?? ""
  return (
    error.code === "42703" ||
    error.code === "PGRST204" ||
    msg.includes("profile_completed_at") ||
    (msg.includes("column") && msg.includes("does not exist"))
  )
}

export async function fetchProfileCompletionRow(
  supabase: SupabaseClient,
  userId: string,
): Promise<ProfileCompletionFetchResult> {
  const withColumn = await supabase
    .from("profiles")
    .select("display_name, avatar_url, profile_completed_at, email")
    .eq("id", userId)
    .maybeSingle()

  if (!withColumn.error) {
    return {
      profile: (withColumn.data as ProfileCompletionRow | null) ?? null,
      hasCompletionColumn: true,
      error: null,
    }
  }

  if (isMissingProfileCompletedColumnError(withColumn.error)) {
    const fallback = await supabase
      .from("profiles")
      .select("display_name, avatar_url, email")
      .eq("id", userId)
      .maybeSingle()

    if (fallback.error) {
      return { profile: null, hasCompletionColumn: false, error: fallback.error.message }
    }

    return {
      profile: fallback.data
        ? {
            ...(fallback.data as Omit<ProfileCompletionRow, "profile_completed_at">),
            profile_completed_at: null,
          }
        : null,
      hasCompletionColumn: false,
      error: null,
    }
  }

  return {
    profile: null,
    hasCompletionColumn: true,
    error: withColumn.error.message,
  }
}

export async function resolveGoogleProfileSetupRequired(
  supabase: SupabaseClient,
  user: User,
): Promise<boolean> {
  if (!isGoogleAuthUser(user)) return false
  if (hasCompletedProfileUsername(user)) return false

  const { profile, hasCompletionColumn, error } = await fetchProfileCompletionRow(
    supabase,
    user.id,
  )

  if (error && !profile) {
    return isRecentOAuthSignup(user)
  }

  return userNeedsGoogleProfileCompletion(user, profile, { hasCompletionColumn })
}

export const COMPLETE_PROFILE_PATH = "/auth/complete-profile"
